# Generated by Django 6.0.2 on 2026-02-17 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_name', models.CharField(choices=[('metatrader4', 'MetaTrader 4'), ('metatrader5', 'MetaTrader 5'), ('ctrader', 'cTrader'), ('mock', 'Mock Broker')], help_text='Broker platform name', max_length=50)),
                ('account_id', models.CharField(help_text='Broker account ID or login', max_length=100)),
                ('account_name', models.CharField(blank=True, help_text='Display name for this account', max_length=100)),
                ('encrypted_api_key', models.BinaryField(help_text='Encrypted API key or password')),
                ('server', models.CharField(blank=True, help_text='Broker server (for MT4/MT5)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active for trading')),
                ('is_demo', models.BooleanField(default=True, help_text='Whether this is a demo account')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Account balance (updated periodically)', max_digits=15)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last time account was synchronized', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_accounts',
                'indexes': [models.Index(fields=['user', 'is_active'], name='broker_acco_user_id_ec686d_idx'), models.Index(fields=['broker_name', 'is_active'], name='broker_acco_broker__e03a44_idx')],
                'unique_together': {('user', 'broker_name', 'account_id')},
            },
        ),
    ]
