# Generated by Django 6.0.2 on 2026-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccount',
            name='account_id',
            field=models.CharField(editable=False, help_text='Auto-generated broker account ID', max_length=100, unique=True),
        ),
    ]
