# Generated by Django 6.0.2 on 2026-02-17 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='Trading action: BUY or SELL', max_length=4)),
                ('instrument', models.CharField(help_text='Trading instrument e.g., EURUSD, GBPUSD', max_length=20)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, help_text='Optional entry price from signal', max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=4, help_text='Stop loss price', max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=4, help_text='Take profit price', max_digits=12)),
                ('raw_signal', models.TextField(help_text='Original signal text received via webhook')),
                ('is_valid', models.BooleanField(default=False, help_text='Whether the signal passed validation')),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Validation error messages if signal is invalid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='trading_sig_user_id_4d3802_idx'), models.Index(fields=['instrument', 'action'], name='trading_sig_instrum_ec2879_idx'), models.Index(fields=['is_valid', 'created_at'], name='trading_sig_is_vali_3a5b61_idx')],
            },
        ),
    ]
