# Generated by Django 6.0.2 on 2026-02-17 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(help_text='Unique order ID from broker or system generated', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=4, help_text='Actual execution price', max_digits=12, null=True)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When order was executed', null=True)),
                ('volume', models.DecimalField(decimal_places=2, default=1.0, help_text='Order volume/lot size', max_digits=10)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=4, help_text='Current or final P&L', max_digits=12, null=True)),
                ('commission', models.DecimalField(decimal_places=4, default=0, help_text='Broker commission', max_digits=10)),
                ('swap', models.DecimalField(decimal_places=4, default=0, help_text='Swap/rollover fees', max_digits=10)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When order was closed', null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, help_text='Price at which order was closed', max_digits=12, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected')),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='brokers.brokeraccount')),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='signals.tradingsignal')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_by', models.CharField(default='system', help_text='What triggered the status change', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'db_table': 'order_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_account', 'status'], name='orders_broker__49fdac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['executed_at'], name='orders_execute_35cb9a_idx'),
        ),
    ]
