# Generated by Django 6.0.2 on 2026-02-17 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('order_executed', 'Order Executed'), ('order_closed', 'Order Closed'), ('order_rejected', 'Order Rejected'), ('signal_received', 'Signal Received'), ('account_connected', 'Account Connected'), ('system_alert', 'System Alert')], max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was marked as read', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('related_order', models.ForeignKey(blank=True, help_text='Related order if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx'), models.Index(fields=['priority', 'is_read'], name='notificatio_priorit_95c9c5_idx')],
            },
        ),
    ]
